#------------------------------------------
# Bindings
#------------------------------------------
# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file
unbind r
bind r source-file ~/.tmux.conf

#------------------------------------------
# Other stuff
#------------------------------------------

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Status highlight
set -g status-right '#{prefix_highlight} | %a %Y-%m-%d %H:%M'

#-------------------------------------------
# Plugins
#-------------------------------------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "arcticicestudio/nord-tmux"
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'